<?php

namespace App\Libraries;

use CodeIgniter\Database\Seeder;
use App\Models\UserModel;
use Config\Database;
use Config\Services;

class Installer
{
    public const LOCK_FILE = WRITEPATH . 'installed.lock';

    public static function isInstalled(): bool
    {
        return is_file(self::LOCK_FILE);
    }

    public static function markInstalled(): void
    {
        file_put_contents(self::LOCK_FILE, json_encode([
            'installed_at' => date('c'),
            'version'      => '1.0.0',
        ], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));
    }

    public static function clearInstallLock(): void
    {
        if (is_file(self::LOCK_FILE)) {
            unlink(self::LOCK_FILE);
        }
    }

    /**
     * Drop every table in the configured database for a clean reinstall.
     */
    public static function resetDatabase(): ?string
    {
        try {
            $db    = Database::connect();
            $forge = Database::forge();

            $tables = $db->listTables();

            if ($tables === []) {
                return null;
            }

            $db->disableForeignKeyChecks();

            foreach ($tables as $table) {
                $forge->dropTable($table, true);
            }

            $db->enableForeignKeyChecks();

            return null;
        } catch (\Throwable $e) {
            return $e->getMessage();
        }
    }

    public static function clearAuthSession(): void
    {
        session()->remove('user_id');
        session()->remove('user_name');
        session()->remove('is_platform_admin');
        session()->remove('current_tenant_id');
    }

    /**
     * @return list<array{key: string, label: string, passed: bool}>
     */
    public static function getRequirements(): array
    {
        $envPath   = ROOTPATH . '.env';
        $envExists = is_file($envPath);

        return [
            ['key' => 'php', 'label' => lang('Install.req_php', [PHP_VERSION]), 'passed' => version_compare(PHP_VERSION, '8.1.0', '>=')],
            ['key' => 'vendor', 'label' => lang('Install.req_vendor'), 'passed' => is_file(ROOTPATH . 'vendor/autoload.php')],
            ['key' => 'mysqli', 'label' => lang('Install.req_mysqli'), 'passed' => extension_loaded('mysqli')],
            ['key' => 'mbstring', 'label' => lang('Install.req_mbstring'), 'passed' => extension_loaded('mbstring')],
            ['key' => 'intl', 'label' => lang('Install.req_intl'), 'passed' => extension_loaded('intl')],
            ['key' => 'json', 'label' => lang('Install.req_json'), 'passed' => extension_loaded('json')],
            ['key' => 'curl', 'label' => lang('Install.req_curl'), 'passed' => extension_loaded('curl')],
            ['key' => 'writable', 'label' => lang('Install.req_writable'), 'passed' => is_writable(WRITEPATH)],
            ['key' => 'env', 'label' => lang('Install.req_env'), 'passed' => ! $envExists || is_writable($envPath)],
        ];
    }

    public static function allRequirementsPassed(): bool
    {
        foreach (self::getRequirements() as $requirement) {
            if (! $requirement['passed']) {
                return false;
            }
        }

        return true;
    }

    public static function testDatabase(array $config): ?string
    {
        try {
            $port   = (int) ($config['port'] ?? 3306);
            $mysqli = @new \mysqli(
                $config['hostname'],
                $config['username'],
                $config['password'],
                $config['database'],
                $port,
            );

            if ($mysqli->connect_error) {
                return $mysqli->connect_error;
            }

            $mysqli->set_charset('utf8mb4');
            $mysqli->close();

            return null;
        } catch (\Throwable $e) {
            return $e->getMessage();
        }
    }

    public static function generateEncryptionKey(): string
    {
        return 'hex2bin:' . bin2hex(random_bytes(32));
    }

    public static function writeEnvFile(array $data): bool
    {
        $baseURL       = self::normalizeBaseUrl($data['baseURL']);
        $baseURL       = self::escapeEnvValue($baseURL);
        $hostname      = self::escapeEnvValue($data['hostname']);
        $database      = self::escapeEnvValue($data['database']);
        $username      = self::escapeEnvValue($data['username']);
        $password      = self::escapeEnvValue($data['password']);
        $port          = (int) ($data['port'] ?? 3306);
        $encryptionKey = $data['encryption_key'];
        $forceHttps    = str_starts_with($data['baseURL'], 'https://') ? 'true' : 'false';

        $content = <<<ENV
#--------------------------------------------------------------------
# BizPanel — generated by web installer
#--------------------------------------------------------------------

CI_ENVIRONMENT = production

app.baseURL = '{$baseURL}'
app.forceGlobalSecureRequests = {$forceHttps}
app.defaultLocale = fa

database.default.hostname = {$hostname}
database.default.database = {$database}
database.default.username = {$username}
database.default.password = {$password}
database.default.DBDriver = MySQLi
database.default.DBPrefix =
database.default.port = {$port}

encryption.key = {$encryptionKey}

session.driver = 'CodeIgniter\\Session\\Handlers\\FileHandler'
ENV;

        return file_put_contents(ROOTPATH . '.env', $content) !== false;
    }

    public static function runMigrations(): ?string
    {
        try {
            $migrate = Services::migrations();
            $migrate->latest();

            return null;
        } catch (\Throwable $e) {
            return $e->getMessage();
        }
    }

    public static function seedModules(): void
    {
        $seeder = Database::seeder();
        $seeder->call('ModuleSeeder');
    }

    public static function createAdmin(array $admin): int
    {
        $userModel = new UserModel();

        $id = $userModel->insert([
            'name'              => $admin['name'],
            'email'             => $admin['email'],
            'password'          => password_hash($admin['password'], PASSWORD_DEFAULT),
            'locale'            => 'fa',
            'theme'             => 'system',
            'is_platform_admin' => 1,
            'status'            => 'active',
        ]);

        if ($id === false) {
            throw new \RuntimeException(implode(' ', $userModel->errors()));
        }

        return (int) $id;
    }

    public static function seedDemoData(int $adminId): void
    {
        $seeder = new \App\Database\Seeds\DemoDataSeeder(config(\Config\Database::class));
        $seeder->setAdminId($adminId)->run();

        $roleSeeder = new \App\Database\Seeds\RoleDemoSeeder(config(\Config\Database::class));
        $roleSeeder->run();
    }

    public static function detectBaseUrl(): string
    {
        $scheme = 'http';

        if (
            (! empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
            || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strtolower($_SERVER['HTTP_X_FORWARDED_PROTO']) === 'https')
            || (isset($_SERVER['HTTP_X_FORWARDED_SSL']) && $_SERVER['HTTP_X_FORWARDED_SSL'] === 'on')
        ) {
            $scheme = 'https';
        }

        $host = $_SERVER['HTTP_HOST'] ?? 'localhost';

        $script = str_replace('\\', '/', $_SERVER['SCRIPT_NAME'] ?? '/index.php');
        $base   = rtrim(str_replace(basename($script), '', $script), '/');

        if ($base === '/') {
            $base = '';
        }

        if (str_ends_with($base, '/public')) {
            $base = substr($base, 0, -7);
        }

        return self::normalizeBaseUrl($scheme . '://' . $host . $base . '/');
    }

    public static function normalizeBaseUrl(string $url): string
    {
        $url = trim($url);

        if ($url === '') {
            return $url;
        }

        $url = rtrim($url, '/') . '/';
        $url = preg_replace('#^(https?://[^/]+)/public(/|$)#i', '$1/', $url) ?? $url;

        return rtrim($url, '/') . '/';
    }

    public static function shouldOverrideBaseUrl(string $configuredBaseUrl): bool
    {
        if (is_cli() || ! isset($_SERVER['HTTP_HOST'])) {
            return false;
        }

        $configuredBaseUrl = self::normalizeBaseUrl($configuredBaseUrl);
        $configuredPath    = parse_url($configuredBaseUrl, PHP_URL_PATH) ?? '/';

        if (str_contains($configuredPath, '/public')) {
            return true;
        }

        $configuredHost = parse_url($configuredBaseUrl, PHP_URL_HOST);

        if (! is_string($configuredHost) || $configuredHost === '') {
            return true;
        }

        $configuredHost = strtolower($configuredHost);
        $currentHost    = strtolower(explode(':', $_SERVER['HTTP_HOST'])[0]);

        if (in_array($configuredHost, ['localhost', '127.0.0.1'], true)) {
            return $currentHost !== $configuredHost;
        }

        return $currentHost !== '' && $configuredHost !== $currentHost;
    }

    private static function escapeEnvValue(string $value): string
    {
        if (preg_match('/[\s#="\']/', $value)) {
            return '"' . addcslashes($value, "\"\\") . '"';
        }

        return $value;
    }
}
